package com.purple_dog.mvp.entities;

public enum NotificationType {
    BID_PLACED,
    BID_OUTBID,
    BID_WON,
    BID_LOST,
    AUCTION_ENDING_SOON,
    AUCTION_ENDED,
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    OFFER_REJECTED,
    ORDER_CREATED,
    ORDER_CONFIRMED,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    ITEM_SHIPPED,
    ITEM_DELIVERED,
    MESSAGE_RECEIVED,
    PRODUCT_VALIDATED,
    PRODUCT_REJECTED,
    ALERT_MATCH,
    ACCOUNT_VERIFIED,
    TICKET_RESPONSE,
    SYSTEM
}
